apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./apps/hello"
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-repo
  targetNamespace: default
